secrets:
  sessionSecret: "49f06f8db4b3b2d794d2a4197bcfef2e"
  magicLinkSecret: "b234271a037c8d882eb7af83e18f7d4c"
  encryptionKey: "56e0c14374ae2222408148a93e119ec6"
  managedWorkerSecret: "c5b71fe7a3c75dc7cda348ee2d57eb7d"


global:
  storageClass: "managed-csi-premium"

webapp:
  appOrigin: "https://trigger.testing-ai.online"
  loginOrigin: "https://trigger.testing-ai.online"
  apiOrigin: "https://trigger.testing-ai.online"


  ingress:
    enabled: false

  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi

postgres:
  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "managed-csi-premium"
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi

redis:
  master:
    persistence:
      enabled: false
   
clickhouse:
  secure: false
  protocol: http
  persistence:
    enabled: true
    size: 20Gi
    storageClass: "managed-csi-premium"

  resources:
    limits:
      cpu: 4000m
      memory: 16Gi
    requests:
      cpu: 2000m
      memory: 8Gi

s3:
  auth:
    rootUser: "admin"
    rootPassword: 'WcW£f#1G5R#.2~7-n'
    accessKeyId: "trigger-s3-access"
    secretAccessKey: "trigger-s3-secret-key-fort"
  persistence:
    enabled: true
    size: 25Gi
    storageClass: "managed-csi"

registry:
  enabled: false
  external:
    host: "wasalacr.azurecr.io"
    auth:
      enabled: true
      secretName: "acr-secret"
  repositoryNamespace: "trigger-tasks"


supervisor:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi